name: Build and Deploy to Azure

env:
  AZURE_CONTAINER_REGISTRY_NAME: "syukayacr240218"  # set this to the name of your Azure Container Registry
  AZURE_CONTAINER_REGISTRY: "syukayacr240218.azurecr.io" # Container Registry URI
  AZURE_CONTAINER_REGISTRY_PASSWORD: "oCSV5cYlQGuNHo3lPXGv3hnS90/qwifOsPtBrCdnID+ACRDLsJrN"  
  CONTAINER_NAME: "hello-world"
  RESOURCE_GROUP: "github-actions-demo-rg"
  CLUSTER_NAME: "syukay-aks-cluster"
  DEPLOYMENT_MANIFEST_PATH: "kubernetes"
  AZURE_CLIENT_ID: "b876527f-8e28-4842-9d34-80f07f9a9d05"
  AZURE_TENANT_ID: "439966cb-1aa0-41de-82bb-f8490c06d7bf"
  AZURE_SUBSCRIPTION_ID: "afa1eee0-c0b7-4b25-b225-d0e4d63b1a84"

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  buildImage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          username: ${{ env.AZURE_CONTAINER_REGISTRY_NAME }}

          password: ${{ env.AZURE_CONTAINER_REGISTRY_PASSWORD }}

          login-server:  ${{ env.AZURE_CONTAINER_REGISTRY }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with:
          push: true
          tags: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}
          file: ./Dockerfile 

  deploy:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      id-token: write

    environment: Production
    needs: [buildImage]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25'
          
      - name: Azure Kubernetes set context
        uses: azure/aks-set-context@v3
        with: 
          # Resource Group Name
          resource-group: ${{ env.RESOURCE_GROUP }}
          # AKS Cluster Name
          cluster-name: ${{ env.CLUSTER_NAME }}
          # Get cluster admin credentials. Values: true or false
          admin: 'false'
          # Enables kubelogin for non-admin user scenario. Values: true or false
          use-kubelogin: 'true'

      - name: envsubst-action
        uses: danielr1996/envsubst-action@1.1.0
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          AZURE_CONTAINER_REGISTRY_NAME: ${{ env.AZURE_CONTAINER_REGISTRY_NAME }}
          AZURE_CONTAINER_REGISTRY: ${{ env.AZURE_CONTAINER_REGISTRY }}
        with:
          input:
            ${{ env.DEPLOYMENT_MANIFEST_PATH }}/hello-world-deployment.yaml
          output:
            hello-world-deployment.yaml 
          
      # Deploys application based on given manifest file
      - name: Deploys application
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: |
            hello-world-deployment.yaml
            ${{ env.DEPLOYMENT_MANIFEST_PATH }}/hello-world-service.yaml
          images: |
            ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}
